;;; vala-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vala-mode.el

(add-to-list 'auto-mode-alist '("\\.vala\\'" . vala-mode))
(add-to-list 'auto-mode-alist '("\\.vapi\\'" . vala-mode))
(c-add-style "vala" '("linux" (c-comment-only-line-offset 0 . 0) (c-offsets-alist (func-decl-cont . ++))))
(autoload 'vala-mode "vala-mode" "\
Major mode for editing Vala code.
Based on CC Mode.

The hook `c-mode-common-hook' is run with no args at mode
initialization, then `vala-mode-hook'.

Key bindings:
\\{vala-mode-map}" t)
(register-definition-prefixes "vala-mode" '("c-filter-ops" "vala-"))

;;; End of scraped data

(provide 'vala-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vala-mode-autoloads.el ends here
